// Code generated by iso8583gen; DO NOT EDIT.

package main

import (
	"bytes"

	"github.com/Pay8583/iso8583"
	"github.com/Pay8583/iso8583/spec"
)

func (m *AuthRequest) MarshalISO8583(p *spec.Protocol) ([]byte, error) {
	var buf bytes.Buffer
	w := iso8583.NewWriter(p, &buf)

	if err := w.WriteMTI(uint(m.MTI)); err != nil {
		return nil, err
	}

	if m.PAN != "" {
		if err := w.WriteString(2, m.PAN); err != nil {
			return nil, err
		}
	}
	if m.ProcCode != "" {
		if err := w.WriteString(3, m.ProcCode); err != nil {
			return nil, err
		}
	}
	if m.Amount != 0 {
		if err := w.WriteInt(4, int64(m.Amount)); err != nil {
			return nil, err
		}
	}
	if m.STAN != "" {
		if err := w.WriteString(11, m.STAN); err != nil {
			return nil, err
		}
	}
	if m.TimeLocal != "" {
		if err := w.WriteString(12, m.TimeLocal); err != nil {
			return nil, err
		}
	}
	if m.DateLocal != "" {
		if err := w.WriteString(13, m.DateLocal); err != nil {
			return nil, err
		}
	}
	if m.Track2 != "" {
		if err := w.WriteString(35, m.Track2); err != nil {
			return nil, err
		}
	}
	if m.RetRefNum != "" {
		if err := w.WriteString(37, m.RetRefNum); err != nil {
			return nil, err
		}
	}
	if m.TerminalID != "" {
		if err := w.WriteString(41, m.TerminalID); err != nil {
			return nil, err
		}
	}
	if m.CurrencyCode != "" {
		if err := w.WriteString(49, m.CurrencyCode); err != nil {
			return nil, err
		}
	}

	if err := w.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func (m *AuthRequest) UnmarshalISO8583(data []byte, p *spec.Protocol) error {
	r := iso8583.NewReader(p, bytes.NewReader(data))

	mti, err := r.ReadMTI()
	if err != nil {
		return err
	}
	m.MTI = uint(mti)

	present, err := r.PresentFields()
	if err != nil {
		return err
	}
	for _, n := range present {
		switch n {
		case 2:
			if err := r.ReadString(2, &m.PAN); err != nil {
				return err
			}
		case 3:
			if err := r.ReadString(3, &m.ProcCode); err != nil {
				return err
			}
		case 4:
			if err := r.ReadInt(4, &m.Amount); err != nil {
				return err
			}
		case 11:
			if err := r.ReadString(11, &m.STAN); err != nil {
				return err
			}
		case 12:
			if err := r.ReadString(12, &m.TimeLocal); err != nil {
				return err
			}
		case 13:
			if err := r.ReadString(13, &m.DateLocal); err != nil {
				return err
			}
		case 35:
			if err := r.ReadString(35, &m.Track2); err != nil {
				return err
			}
		case 37:
			if err := r.ReadString(37, &m.RetRefNum); err != nil {
				return err
			}
		case 41:
			if err := r.ReadString(41, &m.TerminalID); err != nil {
				return err
			}
		case 49:
			if err := r.ReadString(49, &m.CurrencyCode); err != nil {
				return err
			}
		}
	}

	return nil
}
