package spec

import "github.com/Pay8583/iso8583/encoding"

// V1987 is the ISO 8583:1987 protocol definition with ASCII MTI and hex bitmap.
// Fields 2–64 are defined; no secondary bitmap.
var V1987 = Protocol{
	Name:    "1987",
	Version: "1987",
	MTI:     ASCIIMTI,
	Bitmap:  HexBitmap,
	Fields: []Field{
		{Name: "PAN", Len: LVAR(19, encoding.MustGet("bcd")), Valid: N, Value: ASCII, Secure: true},
		{Name: "ProcessingCode", Len: Fixed(6, '0'), Valid: N, Value: ASCII},
		{Name: "AmountTransaction", Len: Fixed(12, '0'), Valid: N, Value: ASCII},
		{Name: "AmountSettlement", Len: Fixed(12, '0'), Valid: N, Value: ASCII},
		{Name: "AmountCardholderBilling", Len: Fixed(12, '0'), Valid: N, Value: ASCII},
		{Name: "TransmissionDateTime", Len: Fixed(10, '0'), Valid: N, Value: ASCII},
		{Name: "AmountCardholderBillingFee", Len: Fixed(8, '0'), Valid: N, Value: ASCII},
		{Name: "ConversionRateSettlement", Len: Fixed(8, '0'), Valid: N, Value: ASCII},
		{Name: "ConversionRateCardholderBilling", Len: Fixed(8, '0'), Valid: N, Value: ASCII},
		{Name: "STAN", Len: Fixed(6, '0'), Valid: N, Value: ASCII},
		{Name: "LocalTransactionTime", Len: Fixed(6, '0'), Valid: N, Value: ASCII},
		{Name: "LocalTransactionDate", Len: Fixed(4, '0'), Valid: N, Value: ASCII},
		{Name: "ExpirationDate", Len: Fixed(4, '0'), Valid: N, Value: ASCII, Secure: true},
		{Name: "SettlementDate", Len: Fixed(4, '0'), Valid: N, Value: ASCII},
		{Name: "CurrencyConversionDate", Len: Fixed(4, '0'), Valid: N, Value: ASCII},
		{Name: "CaptureDate", Len: Fixed(4, '0'), Valid: N, Value: ASCII},
		{Name: "MerchantType", Len: Fixed(4, '0'), Valid: N, Value: ASCII},
		{Name: "AcquiringInstitutionCountry", Len: Fixed(3, '0'), Valid: N, Value: ASCII},
		{Name: "PANExtendedCountry", Len: Fixed(3, '0'), Valid: N, Value: ASCII},
		{Name: "ForwardingInstitutionCountry", Len: Fixed(3, '0'), Valid: N, Value: ASCII},
		{Name: "PointOfServiceEntryMode", Len: Fixed(3, '0'), Valid: N, Value: ASCII},
		{Name: "ApplicationPANSequenceNumber", Len: Fixed(3, '0'), Valid: N, Value: ASCII},
		{Name: "FunctionCode", Len: Fixed(3, '0'), Valid: N, Value: ASCII},
		{Name: "PointOfServiceConditionCode", Len: Fixed(2, '0'), Valid: N, Value: ASCII},
		{Name: "PointOfServiceCaptureCode", Len: Fixed(2, '0'), Valid: N, Value: ASCII},
		{Name: "AuthorizingIdentificationResponseLength", Len: Fixed(1, '0'), Valid: N, Value: ASCII},
		{Name: "AmountTransactionFee", Len: Fixed(9, '0'), Valid: XN, Value: ASCII},
		{Name: "AmountSettlementFee", Len: Fixed(9, '0'), Valid: XN, Value: ASCII},
		{Name: "AmountTransactionProcessingFee", Len: Fixed(9, '0'), Valid: XN, Value: ASCII},
		{Name: "AmountSettlementProcessingFee", Len: Fixed(9, '0'), Valid: XN, Value: ASCII},
		{Name: "AcquiringInstitutionID", Len: LVAR(11, encoding.MustGet("bcd")), Valid: N, Value: ASCII},
		{Name: "ForwardingInstitutionID", Len: LVAR(11, encoding.MustGet("bcd")), Valid: N, Value: ASCII},
		{Name: "PANExtended", Len: LVAR(28, encoding.MustGet("bcd")), Valid: NS, Value: Text},
		{Name: "Track2Data", Len: LVAR(37, encoding.MustGet("bcd")), Valid: Z, Value: ASCII, Secure: true},
		{Name: "Track3Data", Len: LVAR(104, encoding.MustGet("bcd")), Valid: ANS, Value: Text, Secure: true},
		{Name: "RetrievalReferenceNumber", Len: Fixed(12, ' '), Valid: ANS, Value: Text},
		{Name: "AuthorizationIdentificationResponse", Len: Fixed(6, ' '), Valid: ANS, Value: Text},
		{Name: "ResponseCode", Len: Fixed(2, ' '), Valid: ANS, Value: Text},
		{Name: "ServiceRestrictionCode", Len: Fixed(3, ' '), Valid: ANS, Value: Text},
		{Name: "CardAcceptorTerminalID", Len: Fixed(8, ' '), Valid: ANS, Value: Text},
		{Name: "CardAcceptorID", Len: Fixed(15, ' '), Valid: ANS, Value: Text},
		{Name: "CardAcceptorNameLocation", Len: Fixed(40, ' '), Valid: ANS, Value: Text},
		{Name: "AdditionalResponseData", Len: LVAR(1000, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "Track1Data", Len: LVAR(76, encoding.MustGet("bcd")), Valid: ANS, Value: Text, Secure: true},
		{Name: "AdditionalDataISO", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "AdditionalDataNational", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "AdditionalDataPrivate", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "CurrencyCodeTransaction", Len: Fixed(3, ' '), Valid: ANS, Value: Text},
		{Name: "CurrencyCodeSettlement", Len: Fixed(3, ' '), Valid: ANS, Value: Text},
		{Name: "CurrencyCodeCardholderBilling", Len: Fixed(3, ' '), Valid: ANS, Value: Text},
		{Name: "PINData", Len: Fixed(16, 0x00), Valid: B, Value: Hex, Secure: true},
		{Name: "SecurityControlInfo", Len: Fixed(16, '0'), Valid: N, Value: ASCII, Secure: true},
		{Name: "AdditionalAmounts", Len: LVAR(120, encoding.MustGet("bcd")), Valid: ANS, Value: Text, Secure: true},
		{Name: "ICCData", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text, Secure: true},
		{Name: "ReservedISO56", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "ReservedNational57", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "ReservedNational58", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "ReservedNational59", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "ReservedNational60", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text, Secure: true},
		{Name: "ReservedPrivate61", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text, Secure: true},
		{Name: "ReservedPrivate62", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text, Secure: true},
		{Name: "ReservedPrivate63", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "MAC", Len: Fixed(16, '0'), Valid: B, Value: Hex, Secure: true},
	},
}
