package spec

import "github.com/Pay8583/iso8583/encoding"

// V1993 is the ISO 8583:1993 protocol definition with ASCII MTI, hex bitmap,
// and extended bitmap (fields 2–128).
var V1993 = Protocol{
	Name:    "1993",
	Version: "1993",
	MTI:     ASCIIMTI,
	Bitmap:  HexBitmap,
	Fields: []Field{
		// Fields 2–64 (primary bitmap).
		{Name: "PAN", Len: LVAR(19, encoding.MustGet("bcd")), Valid: N, Value: ASCII, Secure: true},
		{Name: "ProcessingCode", Len: Fixed(6, '0'), Valid: N, Value: ASCII},
		{Name: "AmountTransaction", Len: Fixed(12, '0'), Valid: N, Value: ASCII},
		{Name: "AmountSettlement", Len: Fixed(12, '0'), Valid: N, Value: ASCII},
		{Name: "AmountCardholderBilling", Len: Fixed(12, '0'), Valid: N, Value: ASCII},
		{Name: "TransmissionDateTime", Len: Fixed(10, '0'), Valid: N, Value: ASCII},
		{Name: "AmountCardholderBillingFee", Len: Fixed(8, '0'), Valid: N, Value: ASCII},
		{Name: "ConversionRateSettlement", Len: Fixed(8, '0'), Valid: N, Value: ASCII},
		{Name: "ConversionRateCardholderBilling", Len: Fixed(8, '0'), Valid: N, Value: ASCII},
		{Name: "STAN", Len: Fixed(6, '0'), Valid: N, Value: ASCII},
		{Name: "LocalTransactionTime", Len: Fixed(6, '0'), Valid: N, Value: ASCII},
		{Name: "LocalTransactionDate", Len: Fixed(4, '0'), Valid: N, Value: ASCII},
		{Name: "ExpirationDate", Len: Fixed(4, '0'), Valid: N, Value: ASCII, Secure: true},
		{Name: "SettlementDate", Len: Fixed(4, '0'), Valid: N, Value: ASCII},
		{Name: "CurrencyConversionDate", Len: Fixed(4, '0'), Valid: N, Value: ASCII},
		{Name: "CaptureDate", Len: Fixed(4, '0'), Valid: N, Value: ASCII},
		{Name: "MerchantType", Len: Fixed(4, '0'), Valid: N, Value: ASCII},
		{Name: "AcquiringInstitutionCountry", Len: Fixed(3, '0'), Valid: N, Value: ASCII},
		{Name: "PANExtendedCountry", Len: Fixed(3, '0'), Valid: N, Value: ASCII},
		{Name: "ForwardingInstitutionCountry", Len: Fixed(3, '0'), Valid: N, Value: ASCII},
		{Name: "PointOfServiceEntryMode", Len: Fixed(3, '0'), Valid: N, Value: ASCII},
		{Name: "ApplicationPANSequenceNumber", Len: Fixed(3, '0'), Valid: N, Value: ASCII},
		{Name: "FunctionCode", Len: Fixed(3, '0'), Valid: N, Value: ASCII},
		{Name: "PointOfServiceConditionCode", Len: Fixed(2, '0'), Valid: N, Value: ASCII},
		{Name: "PointOfServiceCaptureCode", Len: Fixed(2, '0'), Valid: N, Value: ASCII},
		{Name: "AuthorizingIdentificationResponseLength", Len: Fixed(1, '0'), Valid: N, Value: ASCII},
		{Name: "AmountTransactionFee", Len: Fixed(9, '0'), Valid: XN, Value: ASCII},
		{Name: "AmountSettlementFee", Len: Fixed(9, '0'), Valid: XN, Value: ASCII},
		{Name: "AmountTransactionProcessingFee", Len: Fixed(9, '0'), Valid: XN, Value: ASCII},
		{Name: "AmountSettlementProcessingFee", Len: Fixed(9, '0'), Valid: XN, Value: ASCII},
		{Name: "AcquiringInstitutionID", Len: LVAR(11, encoding.MustGet("bcd")), Valid: N, Value: ASCII},
		{Name: "ForwardingInstitutionID", Len: LVAR(11, encoding.MustGet("bcd")), Valid: N, Value: ASCII},
		{Name: "PANExtended", Len: LVAR(28, encoding.MustGet("bcd")), Valid: NS, Value: Text},
		{Name: "Track2Data", Len: LVAR(37, encoding.MustGet("bcd")), Valid: Z, Value: ASCII, Secure: true},
		{Name: "Track3Data", Len: LVAR(104, encoding.MustGet("bcd")), Valid: ANS, Value: Text, Secure: true},
		{Name: "RetrievalReferenceNumber", Len: Fixed(12, ' '), Valid: ANS, Value: Text},
		{Name: "AuthorizationIdentificationResponse", Len: Fixed(6, ' '), Valid: ANS, Value: Text},
		{Name: "ResponseCode", Len: Fixed(2, ' '), Valid: ANS, Value: Text},
		{Name: "ServiceRestrictionCode", Len: Fixed(3, ' '), Valid: ANS, Value: Text},
		{Name: "CardAcceptorTerminalID", Len: Fixed(8, ' '), Valid: ANS, Value: Text},
		{Name: "CardAcceptorID", Len: Fixed(15, ' '), Valid: ANS, Value: Text},
		{Name: "CardAcceptorNameLocation", Len: Fixed(40, ' '), Valid: ANS, Value: Text},
		{Name: "AdditionalResponseData", Len: LVAR(1000, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "Track1Data", Len: LVAR(76, encoding.MustGet("bcd")), Valid: ANS, Value: Text, Secure: true},
		{Name: "AdditionalDataISO", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "AdditionalDataNational", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "AdditionalDataPrivate", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "CurrencyCodeTransaction", Len: Fixed(3, ' '), Valid: ANS, Value: Text},
		{Name: "CurrencyCodeSettlement", Len: Fixed(3, ' '), Valid: ANS, Value: Text},
		{Name: "CurrencyCodeCardholderBilling", Len: Fixed(3, ' '), Valid: ANS, Value: Text},
		{Name: "PINData", Len: Fixed(16, 0x00), Valid: B, Value: Hex, Secure: true},
		{Name: "SecurityControlInfo", Len: Fixed(16, '0'), Valid: N, Value: ASCII, Secure: true},
		{Name: "AdditionalAmounts", Len: LVAR(120, encoding.MustGet("bcd")), Valid: ANS, Value: Text, Secure: true},
		{Name: "ICCData", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text, Secure: true},
		{Name: "ReservedISO56", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "ReservedNational57", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "ReservedNational58", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "ReservedNational59", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "ReservedNational60", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text, Secure: true},
		{Name: "ReservedPrivate61", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text, Secure: true},
		{Name: "ReservedPrivate62", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text, Secure: true},
		{Name: "ReservedPrivate63", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "MAC", Len: Fixed(16, '0'), Valid: B, Value: Hex, Secure: true},
		// Fields 65–128 (secondary bitmap). Most are reserved for ISO/national/private use.
		{Name: "SettlementCode", Len: Fixed(1, '0'), Valid: N, Value: ASCII},
		{Name: "ExtendedPaymentCode", Len: Fixed(2, '0'), Valid: N, Value: ASCII},
		{Name: "ReceivingInstitutionCountry", Len: Fixed(3, '0'), Valid: N, Value: ASCII},
		{Name: "SettlementInstitutionCountry", Len: Fixed(3, '0'), Valid: N, Value: ASCII},
		{Name: "NetworkManagementInfoCode", Len: Fixed(3, '0'), Valid: N, Value: ASCII},
		{Name: "MessageNumber", Len: Fixed(4, '0'), Valid: N, Value: ASCII},
		{Name: "LastMessageNumber", Len: Fixed(4, '0'), Valid: N, Value: ASCII},
		{Name: "ActionDate", Len: Fixed(6, '0'), Valid: N, Value: ASCII},
		{Name: "NumberOfCredits", Len: Fixed(10, '0'), Valid: N, Value: ASCII},
		{Name: "CreditsReversalNumber", Len: Fixed(10, '0'), Valid: N, Value: ASCII},
		{Name: "NumberOfDebits", Len: Fixed(10, '0'), Valid: N, Value: ASCII},
		{Name: "DebitsReversalNumber", Len: Fixed(10, '0'), Valid: N, Value: ASCII},
		{Name: "TransferNumber", Len: Fixed(10, '0'), Valid: N, Value: ASCII},
		{Name: "TransferReversalNumber", Len: Fixed(10, '0'), Valid: N, Value: ASCII},
		{Name: "NumberOfInquiries", Len: Fixed(10, '0'), Valid: N, Value: ASCII},
		{Name: "NumberOfAuthorizations", Len: Fixed(10, '0'), Valid: N, Value: ASCII},
		{Name: "CreditsProcessingFeeAmount", Len: Fixed(12, '0'), Valid: N, Value: ASCII},
		{Name: "CreditsTransactionFeeAmount", Len: Fixed(12, '0'), Valid: N, Value: ASCII},
		{Name: "DebitsProcessingFeeAmount", Len: Fixed(12, '0'), Valid: N, Value: ASCII},
		{Name: "DebitsTransactionFeeAmount", Len: Fixed(12, '0'), Valid: N, Value: ASCII},
		{Name: "TotalAmountCredits", Len: Fixed(16, '0'), Valid: N, Value: ASCII},
		{Name: "CreditsReversalAmount", Len: Fixed(16, '0'), Valid: N, Value: ASCII},
		{Name: "TotalAmountDebits", Len: Fixed(16, '0'), Valid: N, Value: ASCII},
		{Name: "DebitsReversalAmount", Len: Fixed(16, '0'), Valid: N, Value: ASCII},
		{Name: "OriginalDataElements", Len: Fixed(42, '0'), Valid: N, Value: ASCII},
		{Name: "FileUpdateCode", Len: Fixed(1, ' '), Valid: ANS, Value: Text},
		{Name: "FileSecurityCode", Len: Fixed(2, ' '), Valid: ANS, Value: Text},
		{Name: "ResponseIndicator", Len: Fixed(5, ' '), Valid: ANS, Value: Text},
		{Name: "ServiceIndicator", Len: Fixed(7, ' '), Valid: ANS, Value: Text},
		{Name: "ReplacementAmounts", Len: Fixed(42, ' '), Valid: ANS, Value: Text},
		{Name: "MessageSecurityCode", Len: Fixed(16, '0'), Valid: B, Value: Hex, Secure: true},
		{Name: "NetSettlementAmount", Len: Fixed(17, '0'), Valid: XN, Value: ASCII},
		{Name: "Payee", Len: Fixed(25, ' '), Valid: ANS, Value: Text},
		{Name: "SettlementInstitutionID", Len: LVAR(11, encoding.MustGet("bcd")), Valid: N, Value: ASCII},
		{Name: "ReceivingInstitutionID", Len: LVAR(11, encoding.MustGet("bcd")), Valid: N, Value: ASCII},
		{Name: "FileName", Len: LVAR(17, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "AccountIdentification1", Len: LVAR(28, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "AccountIdentification2", Len: LVAR(28, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "TransactionDescription", Len: LVAR(100, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "ReservedISO105", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "ReservedISO106", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "ReservedISO107", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "ReservedISO108", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "ReservedISO109", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "ReservedISO110", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "ReservedISO111", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "ReservedISO112", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "ReservedNational113", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "ReservedNational114", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "ReservedNational115", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "ReservedNational116", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "ReservedNational117", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "ReservedNational118", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "ReservedNational119", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "ReservedNational120", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "ReservedPrivate121", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "ReservedPrivate122", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "ReservedPrivate123", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "ReservedPrivate124", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "ReservedPrivate125", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "ReservedPrivate126", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "ReservedPrivate127", Len: LVAR(999, encoding.MustGet("bcd")), Valid: ANS, Value: Text},
		{Name: "MAC2", Len: Fixed(16, '0'), Valid: B, Value: Hex, Secure: true},
	},
}
